### ISSUE TITLE
install failed

### ISSUE THREAD

**Issue by vpolinov** [corneal64/AC1200-Dual-Band-Wireless-Drivers#1]
Have freshly installed ubuntu 20.10.
Trying to install your driver.
Getting this:

e@ARMADILLO2:~/AC1200-Dual-Band-Wireless-Drivers$ sudo dkms build -m rtl88x2bu -v ${VER}

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
make -j4 KERNELRELEASE=5.8.0-41-generic KVER=5.8.0-41-generic src=/usr/src/rtl88x2bu-5.3.1.....(bad exit status: 2)
ERROR (dkms apport): binary package for rtl88x2bu: 5.3.1 not found
Error! Bad return status for module build on kernel: 5.8.0-41-generic (x86_64)
Consult /var/lib/dkms/rtl88x2bu/5.3.1/build/make.log for more information.

/usr/src/rtl88x2bu-5.3.1/include/rtw_security.h:252:8: error: redefinition of ‘struct sha256_state’
